"""add user_id to documents

Revision ID: a25ca384a7ee
Revises: 
Create Date: 2026-02-19 18:42:24.850979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a25ca384a7ee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('user_id', sa.String(), nullable=True))
    op.add_column('conversations', sa.Column('title', sa.String(), nullable=True))
    op.create_foreign_key(None, 'conversations', 'users', ['user_id'], ['id'])
    op.add_column('documents', sa.Column('user_id', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('original_filename', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('file_type', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('chunk_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('page_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('status', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('summary', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'summary')
    op.drop_column('documents', 'status')
    op.drop_column('documents', 'page_count')
    op.drop_column('documents', 'chunk_count')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'file_type')
    op.drop_column('documents', 'original_filename')
    op.drop_column('documents', 'user_id')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'title')
    op.drop_column('conversations', 'user_id')
    # ### end Alembic commands ###
